language: scala
sudo: required
dist: trusty
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
scala:
  - 2.11.7
sudo: false
sbt_args:  -J-Xms1600m -J-Xmx1600m -J-XX:MaxMetaspaceSize=1024m
services:
    - mongodb

notifications:
  slack: reallyio:5GS2VfddFeJUWmxJ2tHW9ajS
